-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.softcartdimdate
(
    date_id integer NOT NULL,
    date date,
    year integer,
    quarter integer,
    quartername character varying(20) COLLATE pg_catalog."default",
    month integer,
    monthname character varying(20) COLLATE pg_catalog."default",
    day integer,
    weekday integer,
    weekdayname character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT softcartdimdate_pkey PRIMARY KEY (date_id)
);

CREATE TABLE IF NOT EXISTS public."softcartDimCategory"
(
    category_id integer,
    category_name character varying,
    PRIMARY KEY (category_id)
);

CREATE TABLE IF NOT EXISTS public."softcartDimItem"
(
    item_id integer,
    item_name character varying,
    PRIMARY KEY (item_id)
);

CREATE TABLE IF NOT EXISTS public."softcartDimCountry"
(
    country_id integer,
    country_name character varying,
    PRIMARY KEY (country_id)
);

CREATE TABLE IF NOT EXISTS public."softcartFactSales"
(
    order_id integer,
    item_id integer NOT NULL,
    country_id integer NOT NULL,
    date_id integer NOT NULL,
    PRIMARY KEY (order_id)
);

ALTER TABLE IF EXISTS public."softcartDimItem"
    ADD FOREIGN KEY (item_id)
    REFERENCES public."softcartDimCategory" (category_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."softcartFactSales"
    ADD FOREIGN KEY (item_id)
    REFERENCES public."softcartDimItem" (item_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."softcartFactSales"
    ADD FOREIGN KEY (country_id)
    REFERENCES public."softcartDimCountry" (country_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."softcartFactSales"
    ADD FOREIGN KEY (date_id)
    REFERENCES public.softcartdimdate (date_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;
